name: Build and push Docker image
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1', '8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PHP Docker images
        uses: docker/build-push-action@v5
        with:
          file: php/Dockerfile
          context: php
          platforms: linux/amd64,linux/arm64
          push: true
          tags: meghsh/php:${{ matrix.php_version }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
